### ISSUE TITLE
Cas où il n'y a aucune tâche disponible

### ISSUE THREAD

**Issue by mean-street** [Vayel/go-make#6]
## L'idée
- l'esclave demande du travail
- si le maître répond qu'il n'y en a pas, il lance alors un serveur pour recevoir une tâche le jour où il y en a
## Question
Une fois qu'il reçoit une tâche, il ferme son serveur, et on repart dans la boucle infinie (quitte à en redémarrer un 3s plus tard) ? 
Ou on garde le serveur ? (Ça c'est pas terrible, autant faire ça pour tout le monde dès le début du coup)

**Comment by mean-street** [comment]
J'ai pas mal avancé (et push sur la branche waitingSlaves). En gros : quand le slave n'a pas de tâche, il lance un serveur, et le master stocke son adresse. Le slave se met en "veille" : il écoute sur un chan (hasTask) et ça le bloque tant qu'il ne se passe rien. Quand le master a une tâche dispo pour ce slave, il appelle "ReceiveTask" dans slave/server.go. Cette méthode stocke la tâche (du coup j'ai transformé task en variable globale de slave/main.go), et ajoute un booléen au chan. Ça réveille le slave, qui continue alors dans sa boucle infinie et exécute la tâche comme n'importe quelle autre.
Vous en pensez quoi ?
Sinon vous vous y prenez comment pour tester ces saloperies ? Quelqu'un s'est chauffé sur Simgrid ?

**Comment by ludovic-carre** [comment]
Godlike

**Comment by Vayel** [comment]
@Mean-Street tu as testé le code ? Il me semble que ça ne fonctionne pas (je n'ai pas testé non plus). [Cette ligne](https://github.com/Vayel/go-make/blob/waitingSlaves/slave/main.go#L65) est bloquante, donc tu n'atteins jamais le channel. Tu peux regarder sur la branche `master` comment j'ai fait. https://github.com/Vayel/go-make/blob/master/master/server.go#L55

Détail : https://github.com/Vayel/go-make/blob/waitingSlaves/slave/main.go#L47. Le port est déjà défini plus haut : https://github.com/Vayel/go-make/blob/waitingSlaves/slave/main.go#L40

Tu envoies la tâche en même temps que tu réveilles l'esclave. Je me demande si on ne devrait pas juste envoyer un message "wake up!" puis laisser l'esclave nous contacter comme il le faisait avant.

Un autre truc : tu [retournes des erreurs](https://github.com/Vayel/go-make/blob/waitingSlaves/master/server.go#L47) dans `master.ReceiveTask` si tu n'arrives pas à réveiller un esclave. Mais l'erreur est retournée à l'esclave qui a rendu son travail. Cet esclave s'en fiche que tu n'aies pas réussi à en réveiller un autre.

**Comment by mean-street** [comment]
Pour les erreurs et le port, effectivement c'était con, je corrige.

Pour le réveil, la différence c'est qu'il n'y a pas de boucle infinie dans le master, mais il y en a une dans le slave : faut que je puisse bloquer sa boucle infinie et la reprendre. Donc soit je quitte la fonction main(), et je la rappelle quand le master le contacte, soit je bloque le slave dans la boucle. Ça change qqch ?

**Comment by Vayel** [comment]
@Mean-Street j'ai pas tout compris. :( "Pour le réveil", ça désigne mon premier pour mon troisième paragraphe ?
